/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author Bane
 */
public class HeaderPanel extends javax.swing.JPanel {
    private final Color backgroundColor = new Color(22, 247, 101);
    private final int width = 800,height=120;
    public HeaderPanel() {
        initComponents();
        setBackground(backgroundColor);
        setSize(width,height);
        prepareLbl1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(128, 255, 130));
        setMinimumSize(new java.awt.Dimension(800, 120));

        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("My Drawing Tool");
        lbl1.setPreferredSize(new java.awt.Dimension(800, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prepareLbl1() {
        Font f = new Font("Monospaced",Font.BOLD,32);
        lbl1.setBackground(backgroundColor);
        lbl1.setFont(f);
        lbl1.setHorizontalAlignment((int) JLabel.CENTER_ALIGNMENT);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl1;
    // End of variables declaration//GEN-END:variables
}
